# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions


on:
  # push:
  #   branches:
  #     - main
  #     - master
  schedule:
  # Not sure if there is a specific time when CRAN checks run
  # It seems around 21:30 CET but since we cannot set it in time zone and it is on UTC
  # I set the time a bit later to also account for time differences (CET-CEST)
    - cron:  '44 23 * * *' 

name: update-report
jobs:
  failures:
    if: "! contains(github.event.commits.*.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install system dependencies
        run:  sudo apt-get install libcurl4-openssl-dev
      # - name: Cache R packages # From https://github.com/r-lib/actions/blob/master/.github/workflows/check-standard.yaml#L50-L56
      #   if: runner.os != 'Windows'
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ env.R_LIBS_USER }}
      #     key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
      #     restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - name: Install dependencies
        # if: ${{ failure() }} # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif
        run: |
          Rscript -e "install.packages(c('rmarkdown', 'ggplot2', 'dplyr', 'forcats', 'tidyr', 'flextable'))"
      - name: git config
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
      - name: Update report
        run: Rscript -e "rmarkdown::render('index.Rmd')"
      - name: Commit results
        run: |
          git commit -am 'Automatic commit to update last checks' 
      - name: Push changes
        run: |
          git push
      - name: History
        run: |
          git checkout history
          git add cran-failing-*.csv
          git commit -m "new data"
          git push
