# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions


on:
  # push:
  #   branches:
  #     - main
  #     - master
  schedule:
    # Desired timezone: "Europe/Madrid" # In case it is used, from https://unix.stackexchange.com/a/504044/260613
    - cron:  '30 6 * * *' # Every day at 7:40 Spain time, be aware of time changes

name: update-report
jobs:
  failures:
    if: "! contains(github.event.commits.*.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install system dependencies
        run:  sudo apt-get install libcurl4-openssl-dev
      - name: Cache R packages # From https://github.com/r-lib/actions/blob/master/.github/workflows/check-standard.yaml#L50-L56
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-2-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-2-
      - name: Install dependencies
        if: ${{ failure() }} # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif
        run: |
          Rscript -e "install.packages(c('remotes'));
          install.packages('rmarkdown');
          install.packages('ggplot2');
          install.packages('dplyr');
          install.packages('ggalluvial');
          install.packages('DT');
      - name: git config
        run: |
          git config --global user.email 'actions@github.com'
          git config --global user.name 'gh-pages committer'
      - name: Update BOE
        run: Rscript -e "rmarkdown::render('index.Rmd')"
      - name: Commit results
        run: |
          git add docs/* || git commit -a -m 'Automatic commit to update last BOE'
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.APPTOKEN }}
